# SCH 빅데이터 공학과 3학년-2학기 텍스트 마이닝
날짜 : 2022-09-07 화요일 15:00 2주 4차시
교수 : 문지훈
학생 : 한태규

# pandas 라이브러리 알아보기

- 결측치 처리
- 열(필드)의 삽입과 제거
- 데이터 정렬 및 병합
- 타 자료구조를 pandas 데이터프레임 형태로 변환
- 색인, 인덱싱, 부분집합
- 데이터 셋 조인 및 차원 변환
- 축의 계층적 라벨링 (Labeling)
- 다양한 포맷으로 입출력 기능과 시계열 함수

# pandas 자료구조
- Series 객체의 문자열 표현
- 왼쪽 : 색인
- 오른쪽 : 색인의 해당하는 값
- 데이터에 색인을 지정하지 않으면, 기본 색인인 정수0에서 데이터의 길이 -1까지의 숫자가 표현됨
- Series의 값과 색인은 values와 index 속성을 통해 얻거나 지정할 수 있음

In [36]:
import pandas as pd

data_series = pd.Series([4, 7, -5, 3])
print(type(data_series))
data_series

<class 'pandas.core.series.Series'>


0    4
1    7
2   -5
3    3
dtype: int64

Series : values와 index속성 확인

In [37]:
data_series.values

array([ 4,  7, -5,  3], dtype=int64)

In [38]:
data_series.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
data_series2 = pd.Series(data=[172, 173, 167, 180],
                         index=["안유진", "장원영", "카리나", "문지훈"])
data_series2

안유진    172
장원영    173
카리나    167
문지훈    180
dtype: int64

Series : 값을 선택하거나 대입할 때 색인을 통해 접근

In [40]:
print(type(data_series2["문지훈"]))
print(data_series2["문지훈"])
data_series2["문지훈"] = 179
data_series2[["안유진", "장원영", "문지훈"]]

<class 'numpy.int64'>
180


안유진    172
장원영    173
문지훈    179
dtype: int64

Series : 누락된 값을 찾을 때도 적용

In [41]:
data_series2.isnull()

안유진    False
장원영    False
카리나    False
문지훈    False
dtype: bool

# Pandas 자료구조
- DataFrame
  - 표와 같은 시트에서 여러개의 컬럼(columns)이 있으며, 각 열은 다른 종류의 자료형(숫자, 문자, 불리언)을 담을 수 있슴
  - 각 행과 열에 관한 고유의 색인을 지니고 있슴
- DataFrame 객체
  - 같은 길이의 리스트에 담긴 사전을 이용하여 쉽게 생성할 수 있음 > 사전 : 파이썬의 한가지 자료형으로 key values를 쌍으로 지님
  - 고유의 key값마다 value를 가지며, key를 통해 해당 value에 접근할 수 있습니다.


In [42]:
data = {
    "Member": ["태연", "써니", "티파니", "윤아", "문지훈"],
    "Year": [1989, 1989, 1989, 1990, 1989]
}
frame = pd.DataFrame(data=data)
frame

Member  Year
0     태연  1989
1     써니  1989
2    티파니  1989
3     윤아  1990
4    문지훈  1989

DataFrame : 원하는 순서대로 열을 지정하면 원하는 순서를 지닌 DataFrame 객체가 생성

In [43]:
frame2 = pd.DataFrame(data=data,
                      columns=["Year", "Member"])
frame2

Year Member
0  1989     태연
1  1989     써니
2  1989    티파니
3  1990     윤아
4  1989    문지훈

DataFrame : 열은 사전 형식의 표기법으로 접근할 수 있음

In [44]:
frame2["Member"]

0     태연
1     써니
2    티파니
3     윤아
4    문지훈
Name: Member, dtype: object

DataFrame : 열과 마찬가지로 행에도 색인을 넣을 수 있음

In [45]:
frame3 = pd.DataFrame(data=data,
                      index=["One", "Two", "Three", "Four", "Five"])
frame3

Member  Year
One       태연  1989
Two       써니  1989
Three    티파니  1989
Four      윤아  1990
Five     문지훈  1989

DataFrame : 행렬 전치(Transpose)도 쉽게 수행할 수 있음

In [46]:
frame3.T

One   Two Three  Four  Five
Member    태연    써니   티파니    윤아   문지훈
Year    1989  1989  1989  1990  1989

DataFrame : drop을 통해 선택한 값이 삭제된 객체르르 얻을 수 있음

In [47]:
frame3.drop(["Five"])

Member  Year
One       태연  1989
Two       써니  1989
Three    티파니  1989
Four      윤아  1990

In [48]:
frame3.drop("Year", axis=1)

Member
One       태연
Two       써니
Three    티파니
Four      윤아
Five     문지훈

DataFrame : 행이나 칼럼의 색인을 알파벳 순으로 정렬하거나 데이터값을 크기에 따라 정렬할 수 있음

In [49]:
frame4 = pd.DataFrame(data=[[1, 3, 2, 5],
                            [4, 2, 6, 1]],
                      index=["Three", "One"],
                      columns=["d", "a", "b", "c"])
frame4

d  a  b  c
Three  1  3  2  5
One    4  2  6  1

DataFrame : 행이나 칼럼의 색인을 알파벳 순으로 정렬하거나 데이터값을 크기에 따라 정렬할 수 있음

In [50]:
frame4.sort_index()

d  a  b  c
One    4  2  6  1
Three  1  3  2  5

In [51]:
frame4.sort_index(axis=1)

a  b  c  d
Three  3  2  5  1
One    2  6  1  4

DataFrame : 정렬은 기본적으로 오름차순으로 되어 있지만, 내림차순으로도 정렬할 수 있음

In [52]:
frame4.sort_index(axis=1, ascending=False)

d  c  b  a
Three  1  5  2  3
One    4  1  6  2

DataFrame : 특정 열의 값에 따라 행들을 정렬할 수 있음

In [53]:
frame4.sort_values(by=["c"])

d  a  b  c
One    4  2  6  1
Three  1  3  2  5

# numpy 라이브러리 알아보기

- numpy 라이브러리
    - Numerical Python의 줄임말
    - 고성능의 과학 계산 컴퓨팅과 데이터 분석에 필수적인 라이브러리
- numpy의 기능들
    - 다차원 배열 ndarray
    - 선형대수, 난수 발생기, 푸리에변환 가능
    - 반복문을 작성할 필요 없이 전체 데이터 배열에 관해 빠른 연산을 제공하는 표준 수학 함수
    - C, C++, 포트란으로 쓰인 코드를 통합하는 도구

- ndarray
    - numpy의 핵심 기능 중 하나인 다차원 배열 개체
    - 파이썬에서 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

In [54]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-1.17725857, -1.3680277 , -1.16789063],
       [ 0.45661079, -0.70320809, -0.28501763]])

ndarray : 자유로운 사칙연산이 가능

In [55]:
data * 2

array([[-2.35451714, -2.7360554 , -2.33578126],
       [ 0.91322158, -1.40641619, -0.57003527]])

In [56]:
data + data + data

array([[-3.53177571, -4.1040831 , -3.50367189],
       [ 1.36983237, -2.10962428, -0.8550529 ]])

shape : 배열의 차원 크기를 확인할 수 있음

In [57]:
data.shape

(2, 3)

In [58]:
data.dtype

dtype('float64')

zeros와 ones주어진 길이나 모양에 각각 0과 1이 들어있는 배열 생성

In [59]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

numpy : 색인을 통해 데이터값에 접근할 수 있음

In [61]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

numpy : 다차원 배열에서도 색인을 통해 데이터 값에 접근하라 수 있음

In [64]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[1]

array([4, 5, 6])

In [66]:
arr2d[1][0]

4

In [67]:
arr2d[1, 0]

4

마지막 색인을 생략하면 반환되는 객체는 상위 차원의데이터를 포함하고 있는 한 차원 낮은 ndarray가 생성됨

In [68]:
arr3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr3d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
arr3d[0]

array([1, 2, 3])

# numpy 다차원 배열 객체
- 슬라이스 색인
    - "시작점 : 끝점" 방식으로 슬라이스를 할 수 있음
    - 시작점이나 끝점 중 하나가 생략되면 데이터의 시작점(0) 또는 끝점(데이터의 길이)으로 자동 할당됨
    - 끝점에 해당하는 색인은 반환되지 않으면 끝점 -1 까지의 색인으로 접근됨 > "2:5"는 2, 3, 4, ":3"은 0, 1, 2, 3, 4, ":3"은 1색인부터 데이터 끝까지

In [70]:
arr2d_tmp = arr2d[:2, 1:]
arr2d_tmp

array([[2, 3],
       [5, 6]])